rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"
eureka-server:
  image:  spring-cloud-netflix-example/eureka-server
  hostname: eureka-server
  ports:
    - "8761:8761"
config-server:
  image:  spring-cloud-netflix-example/config-server
  links:
    - "eureka-server"
    - "rabbitmq"
  volumes:
    - ./config-server/config:/app/config
  ports:
    - "8100:8100"